version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - ./saved_models:/app/saved_models
      - ./mlruns:/app/mlruns
      - ./mlflow_registry:/app/mlflow_registry
      - ./mlflow_artifacts:/app/mlflow_artifacts
      - ./logs:/app/logs
      - ./confusion_analysis:/app/confusion_analysis
      - ./benchmark_results:/app/benchmark_results
      - ./data:/app/data
      - ./evaluation_results:/app/evaluation_results
      - ./api-test-endpoint:/app/api-test-endpoint
      - ./image-test-apprentissage:/app/image-test-apprentissage
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - SECRET_KEY=${SECRET_KEY}
      - MODEL_PATH=/app/saved_models/20250221_132302/ResNet-50_acc78.61_20250221_132302.pth
      # Configuration des utilisateurs initiaux
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CREATE_DEFAULT_USER=${CREATE_DEFAULT_USER}
      - DEFAULT_USERNAME=${DEFAULT_USERNAME}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      # Configuration MLflow
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - MLFLOW_TRACKING_USERNAME=admin
      - MLFLOW_TRACKING_PASSWORD=password
      - MLFLOW_SERVE_ARTIFACTS=true
      - MLFLOW_ARTIFACT_ROOT=/app/artifacts
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ./entrypoint.sh

volumes:
  model-data: 